; INI file, значение должно закрываться ';'
BDName=RIMSUsersLeave; Имя базы данных, где лежат все данные о пользователях
Address=TSD-SQL02-ID; Адрес SQL Server где лежит база
; имена пользователей которые не должны попасть в обработку пишуться через пробел
UserNameEx=user1 user2 user3;
; Credintal для работы с RIMS
domen=ie.corp;
login=LOGIN;
password=S3pasword=;
; Количество потоков которые буду взаимодействовать с РИМС (от 1 до 10)
ThreadsInt = 5;
; Uri для проверочного запроса к RIMS
URI1=https://fim.sib.rual.ru/Export/api/Person/EmployeesAccountsOdata?%24filter=Domain%20eq%20'IE.Corp'%20&%24top=1;
; Uri для полного забора данных временно отсутствующих
;URI2=https://fim.sib.rual.ru/Export/api/Person/Odata?%24filter=Domain%20eq%20'IE.Corp'%20and%20Disabled%20eq%20false%20and%20LeaveType%20ne%20null;
;
; Это запрос на  CompanyName eq 'ЭН+ ДИДЖИТАЛ ООО' and Disabled eq false and LeaveType ne null 
; (чтобы его использовать поставить в URI2 и удалить базу, чтобы она заного создалась уже с ноавми данными)
; https://fim.sib.rual.ru/Export/api/Person/Odata?%24filter=CompanyName%20eq%20'%D0%AD%D0%9D%2B%20%D0%94%D0%98%D0%94%D0%96%D0%98%D0%A2%D0%90%D0%9B%20%D0%9E%D0%9E%D0%9E'%20and%20Disabled%20eq%20false%20and%20LeaveType%20ne%20null
URI2=https://fim.sib.rual.ru/Export/api/Person/Odata?%24filter=CompanyName%20eq%20'%D0%AD%D0%9D%2B%20%D0%94%D0%98%D0%94%D0%96%D0%98%D0%A2%D0%90%D0%9B%20%D0%9E%D0%9E%D0%9E'%20and%20Disabled%20eq%20false%20and%20LeaveType%20ne%20null
; Uri для получения статуса Автоответа от RIMS
URI3=https://kraz-s-rims01.hq.root.ad/api/Exchange/GetOutOfOffice;
; Uri для отправки запросов к РИМС на установку автоответов в Exchange
URI4=https://kraz-s-rims01.hq.root.ad/api/Exchange/SetOutOfOffice;
;
; Раздел Email:  
; Отчет о выполнении работы программы
; Обычно на каком сервере запускается программа то имя и используем
UserFrom=PST-RDP01-I02@enplus.digital;
; Куда будет отправлять письмо 
UserTo=login@digital;
;
UserCc=f1@digital;
; Почтовый шлюз
ServerPost=mail.corp;
; Порт
Port=25;
; файл для записи логинов пользователей которых необходимо исключить из обработки
exUsersFile=exusersfile.txt;
